"""Manages the queue of pending and history tweets."""

import json
import os
import uuid
import logging
from datetime import datetime
import config
import telegram_notifier

logger = logging.getLogger(__name__)

PENDING_FILE = "pending_tweets.json"

def get_pending():
    if not os.path.exists(PENDING_FILE):
        return []
    try:
        with open(PENDING_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []

def save_pending(tweets: list[dict]):
    with open(PENDING_FILE, "w", encoding="utf-8") as f:
        json.dump(tweets, f, indent=2)

def get_history():
    if not os.path.exists(config.TWEET_HISTORY_FILE):
        return []
    try:
        with open(config.TWEET_HISTORY_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []

def save_history(tweets: list[dict]):
    with open(config.TWEET_HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(tweets, f, indent=2)

def get_recent_tweet_texts(limit=50):
    recent_texts = []
    
    pending = get_pending()
    for p in pending[:limit]:
        recent_texts.append(p.get("text", ""))
        
    history = get_history()
    for h in history[:limit]:
        recent_texts.append(h.get("text", ""))
        
    return recent_texts

async def add_pending_tweet(text: str | list[str], module: str):
    """Adds a newly generated tweet (or thread) to the pending queue."""
    pending = get_pending()
    
    # Check if thread
    is_thread = isinstance(text, list)
    display_text = "\n\n---\n\n".join(text) if is_thread else text
    
    # Append ref info manually for display
    ref_info = f"\n\nRef Link: {config.POLYMARKET_REF_LINK}\nRef Code: {config.POLYMARKET_REF_CODE}\nTG: {config.TELEGRAM_LINK}"
    
    item = {
        "id": str(uuid.uuid4()),
        "module": module,
        "text": display_text,
        "full_text": display_text + ref_info, # Includes refs for easy copying
        "is_thread": is_thread,
        "created_at": datetime.utcnow().isoformat()
    }
    
    pending.insert(0, item) # Newest first
    save_pending(pending)
    
    logger.info(f"[tweet_manager] Added new pending tweet from {module}")
    await telegram_notifier.send_message(f"📝 New tweet generated by {module}!\nIt's waiting in the dashboard for you to post.")

def mark_posted(tweet_id: str):
    """Moves a tweet from pending to history."""
    pending = get_pending()
    item = next((t for t in pending if t["id"] == tweet_id), None)
    
    if item:
        pending = [t for t in pending if t["id"] != tweet_id]
        save_pending(pending)
        
        history = get_history()
        item["posted_at"] = datetime.utcnow().isoformat()
        history.insert(0, item)
        save_history(history)
        return True
    return False

def delete_pending(tweet_id: str):
    """Deletes a pending tweet without moving to history."""
    pending = get_pending()
    initial_len = len(pending)
    pending = [t for t in pending if t["id"] != tweet_id]
    if len(pending) < initial_len:
        save_pending(pending)
        return True
    return False
